### ISSUE TITLE
psql:Badges.sql:26220755: ERROR:  duplicate key value violates unique constraint "badges_userid_key"

### ISSUE THREAD

**Issue by supaplextor** [badmonster-nc/stackoverflow_in_pg#1]
I dropped the constraint and the import works fine. One remaining constraint in effect.

stackoverflow=> select * from badges limit 5;
 id | userid | name | date | badgeclass | tagbased 
----+--------+------+------+------------+----------
(0 rows)

stackoverflow=> \ir Badges.sql 
psql:Badges.sql:26220755: ERROR:  duplicate key value violates unique constraint "badges_userid_key"
DETAIL:  Key (userid)=(4591) already exists.
CONTEXT:  COPY badges, line 2727

**Comment by badmonster-nc** [comment]
thks @supaplextor
